-- Generated from pdf_build/data.js. Run after schema.sql.
-- Safe to re-run: uses ON CONFLICT to upsert rather than duplicate.
--
-- This is the original v0 baseline: 26 exercises on a `category` column and
-- 2 programs. Migration 0001_rebuild_library_and_splits.sql then reshapes
-- `exercises` (dropping `category`, renaming `cue`), replaces this content
-- with the full 63-exercise library, and moves the programs into the new
-- splits model. Once that migration has run, this file no longer matches the
-- schema and must not be re-run on its own. It is kept only as the record of
-- what first built the database; migrations are the source of truth from
-- here on.

-- Exercise library --------------------------------------------------

insert into exercises (name, category, cue, video_url) values ('Incline Dumbbell Press', 'Chest', 'Dumbbells at shoulder level, press up to full extension, lower with control, keep chest engaged.', 'https://www.loom.com/share/02e642695ac748c5ae8f3edb2ca2c60c') on conflict (name) do update set category = excluded.category, cue = excluded.cue, video_url = excluded.video_url;
insert into exercises (name, category, cue, video_url) values ('Pec Fly Machine', 'Chest', 'Back against the pad, bring handles together in a wide arc, slight bend in elbows, squeeze the chest at the top.', 'https://www.loom.com/share/bd19ddcac4ad4ea18798f936bc07b366') on conflict (name) do update set category = excluded.category, cue = excluded.cue, video_url = excluded.video_url;
insert into exercises (name, category, cue, video_url) values ('Body Weight Push Up', 'Chest', 'Hands slightly wider than shoulders, body straight, lower your chest to the floor, press back up.', 'https://www.loom.com/share/cea8dda8a6ad451e9539d2a2a285f2a3') on conflict (name) do update set category = excluded.category, cue = excluded.cue, video_url = excluded.video_url;
insert into exercises (name, category, cue, video_url) values ('Cable Standing Tricep Extension', 'Triceps', 'Slight bend in the knees, extend arms fully keeping elbows tucked in, return with control.', 'https://www.loom.com/share/d36c11634e2944cab3cd1d1f834a80d2') on conflict (name) do update set category = excluded.category, cue = excluded.cue, video_url = excluded.video_url;
insert into exercises (name, category, cue, video_url) values ('Cuffed Lateral Raise', 'Shoulders', 'Cuffs on wrists at a low cable, raise arms out to the sides to shoulder height, lead with the delts.', 'https://www.loom.com/share/3364eac20d7d46adb1696e617dad6645') on conflict (name) do update set category = excluded.category, cue = excluded.cue, video_url = excluded.video_url;
insert into exercises (name, category, cue, video_url) values ('Leg Extension Machine', 'Legs', 'Knees aligned with the pivot point, extend the legs fully, lower with control.', 'https://www.loom.com/share/97db6ded80094e2f856461bce6538c3d') on conflict (name) do update set category = excluded.category, cue = excluded.cue, video_url = excluded.video_url;
insert into exercises (name, category, cue, video_url) values ('Chest Supported Landmine Row', 'Back', 'Chest down on an incline bench facing the landmine, pull the bar to your chest keeping elbows close, lower with control.', 'https://www.loom.com/share/9af97f79d35b4457946f220aa1c489e7') on conflict (name) do update set category = excluded.category, cue = excluded.cue, video_url = excluded.video_url;
insert into exercises (name, category, cue, video_url) values ('Lat Pull Down', 'Back', 'Grip slightly wider than shoulders, pull the bar to your chest, control the return.', 'https://www.loom.com/share/61191122b69341acbf44750fabde545d') on conflict (name) do update set category = excluded.category, cue = excluded.cue, video_url = excluded.video_url;
insert into exercises (name, category, cue, video_url) values ('Preacher Curl Machine', 'Biceps', 'Arms on the pad, palms up, curl to full contraction, slow negative.', 'https://www.loom.com/share/de6f8ee687e6422aa34dc0b8410740e0') on conflict (name) do update set category = excluded.category, cue = excluded.cue, video_url = excluded.video_url;
insert into exercises (name, category, cue, video_url) values ('Lying Leg Curl Machine', 'Legs', 'Face down, ankles under the pad, curl your heels toward your glutes, lower with control.', 'https://www.loom.com/share/a6f55b1ae62a41749eb224b346e9fba8') on conflict (name) do update set category = excluded.category, cue = excluded.cue, video_url = excluded.video_url;
insert into exercises (name, category, cue, video_url) values ('Barbell Shrugs', 'Back', 'Barbell at your thighs, shrug your shoulders straight up, brief hold at the top, slow lower.', 'https://www.loom.com/share/0f2d5b8f409141a9b12abed80b8b1dff') on conflict (name) do update set category = excluded.category, cue = excluded.cue, video_url = excluded.video_url;
insert into exercises (name, category, cue, video_url) values ('Seated Calf Raise (Leg Press Machine)', 'Legs', 'Toes on the lower edge of the footplate, heels hanging off, push through the toes to lift the heels, slow lower.', 'https://www.loom.com/share/e63061c2d61841f9813e4c8607e81d18') on conflict (name) do update set category = excluded.category, cue = excluded.cue, video_url = excluded.video_url;
insert into exercises (name, category, cue, video_url) values ('Seated Hip Adduction Machine', 'Legs', 'Thighs against the inner pads, squeeze your legs together, slow return.', 'https://www.loom.com/share/5e96e996bc3b42c5a91b8f97c65576bb') on conflict (name) do update set category = excluded.category, cue = excluded.cue, video_url = excluded.video_url;
insert into exercises (name, category, cue, video_url) values ('Lying Leg Press Machine', 'Legs', 'Feet shoulder width apart on the platform, push through your heels to extend, lower to about 90 degrees at the knee.', 'https://www.loom.com/share/1bfe00452d004cb68d2b02e540b2e954') on conflict (name) do update set category = excluded.category, cue = excluded.cue, video_url = excluded.video_url;
insert into exercises (name, category, cue, video_url) values ('Dumbbell Walking Lunges', 'Legs', 'Step forward, lower until both knees hit 90 degrees, push off the back leg to step through.', 'https://www.loom.com/share/a3c123f6f29542999a0feba5b7edc897') on conflict (name) do update set category = excluded.category, cue = excluded.cue, video_url = excluded.video_url;
insert into exercises (name, category, cue, video_url) values ('Chest Focused Dips', 'Chest', 'Lean forward with elbows flared, lower until your shoulders drop below your elbows, press back up.', 'https://www.loom.com/share/8c069936fa324d11bc4c1ec1abead960') on conflict (name) do update set category = excluded.category, cue = excluded.cue, video_url = excluded.video_url;
insert into exercises (name, category, cue, video_url) values ('Overhead Cable Tricep Extension', 'Triceps', 'Face away from the pulley, extend your arms overhead keeping elbows close to your head, lower with control.', 'https://www.loom.com/share/6f28a66078e34a56bad971919f029329') on conflict (name) do update set category = excluded.category, cue = excluded.cue, video_url = excluded.video_url;
insert into exercises (name, category, cue, video_url) values ('Dumbbell Lateral Raise', 'Shoulders', 'Dumbbells at your sides, raise arms out to shoulder height, slight bend in elbows, lower with control.', 'https://www.loom.com/share/15a88578ee5a4eb6ba48ea3895e67978') on conflict (name) do update set category = excluded.category, cue = excluded.cue, video_url = excluded.video_url;
insert into exercises (name, category, cue, video_url) values ('Shoulder Press Machine', 'Shoulders', 'Back against the pad, press the handles overhead to full extension, lower with control.', 'https://www.loom.com/share/e67e0bc924d4465cb791dded4bc06efd') on conflict (name) do update set category = excluded.category, cue = excluded.cue, video_url = excluded.video_url;
insert into exercises (name, category, cue, video_url) values ('Incline Lying Dumbbell Bicep Curl', 'Biceps', 'Lie back on an incline bench, palms up, curl to your shoulders keeping elbows still, slow lower.', 'https://www.loom.com/share/f150f7cfde1b469f85ce7a0a0f0c1e40') on conflict (name) do update set category = excluded.category, cue = excluded.cue, video_url = excluded.video_url;
insert into exercises (name, category, cue, video_url) values ('Rope Standing Cable Bicep Curl', 'Biceps', 'Rope on a low pulley, palms facing in, curl to your shoulders with elbows fixed, slow lower.', 'https://www.loom.com/share/6ba8358f474346a09e4bea5e404b7cb7') on conflict (name) do update set category = excluded.category, cue = excluded.cue, video_url = excluded.video_url;
insert into exercises (name, category, cue, video_url) values ('Barbell Row', 'Back', 'Hinge at the hips, row the bar to your lower chest keeping elbows close, lower with control.', 'https://www.loom.com/share/0604db8d842d48f689da9cf966635c2d') on conflict (name) do update set category = excluded.category, cue = excluded.cue, video_url = excluded.video_url;
insert into exercises (name, category, cue, video_url) values ('Seated Hip Abduction Machine', 'Legs', 'Legs inside the pads, push outward against the resistance, slow return.', 'https://www.loom.com/share/c4f996625c704926a3440648d3f953b0') on conflict (name) do update set category = excluded.category, cue = excluded.cue, video_url = excluded.video_url;
insert into exercises (name, category, cue, video_url) values ('Seated Leg Curl Machine', 'Legs', 'Back against the pad, ankles secured under the bar, curl your legs downward, squeeze the hamstrings.', 'https://www.loom.com/share/13bf708413874b829d75f89295937c3a') on conflict (name) do update set category = excluded.category, cue = excluded.cue, video_url = excluded.video_url;
insert into exercises (name, category, cue, video_url) values ('Barbell RDL''s', 'Legs', 'Feet hip width apart, hinge at the hips keeping the bar close to your legs, engage glutes and hamstrings to stand.', 'https://www.loom.com/share/5d2d19a51b6843bab4bd7513de818b87') on conflict (name) do update set category = excluded.category, cue = excluded.cue, video_url = excluded.video_url;
insert into exercises (name, category, cue, video_url) values ('Hip Thrust Machine', 'Legs', 'Upper back against the pad, feet flat on the platform, drive through your heels to extend your hips, squeeze glutes at the top.', 'https://www.loom.com/share/79436bc6480643afac233aeb48ea248c') on conflict (name) do update set category = excluded.category, cue = excluded.cue, video_url = excluded.video_url;

-- Programs -----------------------------------------------------------

insert into programs (slug, name, description, days_per_week) values ('superman-6-day', 'Superman 6-Day Split', 'Six days a week, split by muscle group: push, pull, legs, push, pull, and a shoulders/hams/glutes finisher.', 6) on conflict (slug) do update set name = excluded.name, description = excluded.description, days_per_week = excluded.days_per_week;
insert into program_days (program_id, slug, code, name, tag, day_order) select id, 'mon', 'MON', 'Chest & Push', 'Push A', 0 from programs where slug = 'superman-6-day' on conflict (program_id, slug) do update set code = excluded.code, name = excluded.name, tag = excluded.tag, day_order = excluded.day_order;
delete from program_day_exercises where program_day_id = (select id from program_days where program_id = (select id from programs where slug = 'superman-6-day') and slug = 'mon');
insert into program_day_exercises (program_day_id, exercise_id, position, letter, sets, reps) select pd.id, e.id, 0, 'A', 2, '8-12' from program_days pd, exercises e where pd.program_id = (select id from programs where slug = 'superman-6-day') and pd.slug = 'mon' and e.name = 'Incline Dumbbell Press';
insert into program_day_exercises (program_day_id, exercise_id, position, letter, sets, reps) select pd.id, e.id, 1, 'B', 3, '8-12' from program_days pd, exercises e where pd.program_id = (select id from programs where slug = 'superman-6-day') and pd.slug = 'mon' and e.name = 'Pec Fly Machine';
insert into program_day_exercises (program_day_id, exercise_id, position, letter, sets, reps) select pd.id, e.id, 2, 'C', 2, '8-12' from program_days pd, exercises e where pd.program_id = (select id from programs where slug = 'superman-6-day') and pd.slug = 'mon' and e.name = 'Body Weight Push Up';
insert into program_day_exercises (program_day_id, exercise_id, position, letter, sets, reps) select pd.id, e.id, 3, 'D', 3, '12-15' from program_days pd, exercises e where pd.program_id = (select id from programs where slug = 'superman-6-day') and pd.slug = 'mon' and e.name = 'Cable Standing Tricep Extension';
insert into program_day_exercises (program_day_id, exercise_id, position, letter, sets, reps) select pd.id, e.id, 4, 'E', 2, '12-15' from program_days pd, exercises e where pd.program_id = (select id from programs where slug = 'superman-6-day') and pd.slug = 'mon' and e.name = 'Cuffed Lateral Raise';
insert into program_day_exercises (program_day_id, exercise_id, position, letter, sets, reps) select pd.id, e.id, 5, 'F', 2, '8-12' from program_days pd, exercises e where pd.program_id = (select id from programs where slug = 'superman-6-day') and pd.slug = 'mon' and e.name = 'Leg Extension Machine';

insert into program_days (program_id, slug, code, name, tag, day_order) select id, 'tue', 'TUE', 'Back & Pull', 'Pull A', 1 from programs where slug = 'superman-6-day' on conflict (program_id, slug) do update set code = excluded.code, name = excluded.name, tag = excluded.tag, day_order = excluded.day_order;
delete from program_day_exercises where program_day_id = (select id from program_days where program_id = (select id from programs where slug = 'superman-6-day') and slug = 'tue');
insert into program_day_exercises (program_day_id, exercise_id, position, letter, sets, reps) select pd.id, e.id, 0, 'A', 2, '8-12' from program_days pd, exercises e where pd.program_id = (select id from programs where slug = 'superman-6-day') and pd.slug = 'tue' and e.name = 'Chest Supported Landmine Row';
insert into program_day_exercises (program_day_id, exercise_id, position, letter, sets, reps) select pd.id, e.id, 1, 'B', 2, '8-12' from program_days pd, exercises e where pd.program_id = (select id from programs where slug = 'superman-6-day') and pd.slug = 'tue' and e.name = 'Lat Pull Down';
insert into program_day_exercises (program_day_id, exercise_id, position, letter, sets, reps) select pd.id, e.id, 2, 'C', 3, '12-15' from program_days pd, exercises e where pd.program_id = (select id from programs where slug = 'superman-6-day') and pd.slug = 'tue' and e.name = 'Preacher Curl Machine';
insert into program_day_exercises (program_day_id, exercise_id, position, letter, sets, reps) select pd.id, e.id, 3, 'D', 2, '8-12' from program_days pd, exercises e where pd.program_id = (select id from programs where slug = 'superman-6-day') and pd.slug = 'tue' and e.name = 'Lying Leg Curl Machine';
insert into program_day_exercises (program_day_id, exercise_id, position, letter, sets, reps) select pd.id, e.id, 4, 'E', 2, '12-15' from program_days pd, exercises e where pd.program_id = (select id from programs where slug = 'superman-6-day') and pd.slug = 'tue' and e.name = 'Barbell Shrugs';

insert into program_days (program_id, slug, code, name, tag, day_order) select id, 'wed', 'WED', 'Quads & Legs', 'Legs', 2 from programs where slug = 'superman-6-day' on conflict (program_id, slug) do update set code = excluded.code, name = excluded.name, tag = excluded.tag, day_order = excluded.day_order;
delete from program_day_exercises where program_day_id = (select id from program_days where program_id = (select id from programs where slug = 'superman-6-day') and slug = 'wed');
insert into program_day_exercises (program_day_id, exercise_id, position, letter, sets, reps) select pd.id, e.id, 0, 'A', 2, '12-15' from program_days pd, exercises e where pd.program_id = (select id from programs where slug = 'superman-6-day') and pd.slug = 'wed' and e.name = 'Seated Calf Raise (Leg Press Machine)';
insert into program_day_exercises (program_day_id, exercise_id, position, letter, sets, reps) select pd.id, e.id, 1, 'B', 2, '12-15' from program_days pd, exercises e where pd.program_id = (select id from programs where slug = 'superman-6-day') and pd.slug = 'wed' and e.name = 'Seated Hip Adduction Machine';
insert into program_day_exercises (program_day_id, exercise_id, position, letter, sets, reps) select pd.id, e.id, 2, 'C', 3, '8-12' from program_days pd, exercises e where pd.program_id = (select id from programs where slug = 'superman-6-day') and pd.slug = 'wed' and e.name = 'Leg Extension Machine';
insert into program_day_exercises (program_day_id, exercise_id, position, letter, sets, reps) select pd.id, e.id, 3, 'D', 2, '8-12' from program_days pd, exercises e where pd.program_id = (select id from programs where slug = 'superman-6-day') and pd.slug = 'wed' and e.name = 'Lying Leg Press Machine';
insert into program_day_exercises (program_day_id, exercise_id, position, letter, sets, reps) select pd.id, e.id, 4, 'E', 2, '8-12' from program_days pd, exercises e where pd.program_id = (select id from programs where slug = 'superman-6-day') and pd.slug = 'wed' and e.name = 'Dumbbell Walking Lunges';

insert into program_days (program_id, slug, code, name, tag, day_order) select id, 'thu', 'THU', 'Triceps & Push', 'Push B', 3 from programs where slug = 'superman-6-day' on conflict (program_id, slug) do update set code = excluded.code, name = excluded.name, tag = excluded.tag, day_order = excluded.day_order;
delete from program_day_exercises where program_day_id = (select id from program_days where program_id = (select id from programs where slug = 'superman-6-day') and slug = 'thu');
insert into program_day_exercises (program_day_id, exercise_id, position, letter, sets, reps) select pd.id, e.id, 0, 'A', 2, '8-12' from program_days pd, exercises e where pd.program_id = (select id from programs where slug = 'superman-6-day') and pd.slug = 'thu' and e.name = 'Chest Focused Dips';
insert into program_day_exercises (program_day_id, exercise_id, position, letter, sets, reps) select pd.id, e.id, 1, 'B', 2, '12-15' from program_days pd, exercises e where pd.program_id = (select id from programs where slug = 'superman-6-day') and pd.slug = 'thu' and e.name = 'Cable Standing Tricep Extension';
insert into program_day_exercises (program_day_id, exercise_id, position, letter, sets, reps) select pd.id, e.id, 2, 'C', 2, '12-15' from program_days pd, exercises e where pd.program_id = (select id from programs where slug = 'superman-6-day') and pd.slug = 'thu' and e.name = 'Overhead Cable Tricep Extension';
insert into program_day_exercises (program_day_id, exercise_id, position, letter, sets, reps) select pd.id, e.id, 3, 'D', 2, '8-12' from program_days pd, exercises e where pd.program_id = (select id from programs where slug = 'superman-6-day') and pd.slug = 'thu' and e.name = 'Incline Dumbbell Press';
insert into program_day_exercises (program_day_id, exercise_id, position, letter, sets, reps) select pd.id, e.id, 4, 'E', 2, '12-15' from program_days pd, exercises e where pd.program_id = (select id from programs where slug = 'superman-6-day') and pd.slug = 'thu' and e.name = 'Dumbbell Lateral Raise';
insert into program_day_exercises (program_day_id, exercise_id, position, letter, sets, reps) select pd.id, e.id, 5, 'F', 2, '8-12' from program_days pd, exercises e where pd.program_id = (select id from programs where slug = 'superman-6-day') and pd.slug = 'thu' and e.name = 'Shoulder Press Machine';

insert into program_days (program_id, slug, code, name, tag, day_order) select id, 'fri', 'FRI', 'Biceps & Pull', 'Pull B', 4 from programs where slug = 'superman-6-day' on conflict (program_id, slug) do update set code = excluded.code, name = excluded.name, tag = excluded.tag, day_order = excluded.day_order;
delete from program_day_exercises where program_day_id = (select id from program_days where program_id = (select id from programs where slug = 'superman-6-day') and slug = 'fri');
insert into program_day_exercises (program_day_id, exercise_id, position, letter, sets, reps) select pd.id, e.id, 0, 'A', 2, '12-15' from program_days pd, exercises e where pd.program_id = (select id from programs where slug = 'superman-6-day') and pd.slug = 'fri' and e.name = 'Preacher Curl Machine';
insert into program_day_exercises (program_day_id, exercise_id, position, letter, sets, reps) select pd.id, e.id, 1, 'B', 2, '12-15' from program_days pd, exercises e where pd.program_id = (select id from programs where slug = 'superman-6-day') and pd.slug = 'fri' and e.name = 'Incline Lying Dumbbell Bicep Curl';
insert into program_day_exercises (program_day_id, exercise_id, position, letter, sets, reps) select pd.id, e.id, 2, 'C', 2, '12-15' from program_days pd, exercises e where pd.program_id = (select id from programs where slug = 'superman-6-day') and pd.slug = 'fri' and e.name = 'Rope Standing Cable Bicep Curl';
insert into program_day_exercises (program_day_id, exercise_id, position, letter, sets, reps) select pd.id, e.id, 3, 'D', 2, '12-15' from program_days pd, exercises e where pd.program_id = (select id from programs where slug = 'superman-6-day') and pd.slug = 'fri' and e.name = 'Barbell Shrugs';
insert into program_day_exercises (program_day_id, exercise_id, position, letter, sets, reps) select pd.id, e.id, 4, 'E', 2, '8-12' from program_days pd, exercises e where pd.program_id = (select id from programs where slug = 'superman-6-day') and pd.slug = 'fri' and e.name = 'Barbell Row';

insert into program_days (program_id, slug, code, name, tag, day_order) select id, 'sat', 'SAT', 'Shoulders, Hams & Glutes', 'Accessory', 5 from programs where slug = 'superman-6-day' on conflict (program_id, slug) do update set code = excluded.code, name = excluded.name, tag = excluded.tag, day_order = excluded.day_order;
delete from program_day_exercises where program_day_id = (select id from program_days where program_id = (select id from programs where slug = 'superman-6-day') and slug = 'sat');
insert into program_day_exercises (program_day_id, exercise_id, position, letter, sets, reps) select pd.id, e.id, 0, 'A', 2, '12-15' from program_days pd, exercises e where pd.program_id = (select id from programs where slug = 'superman-6-day') and pd.slug = 'sat' and e.name = 'Dumbbell Lateral Raise';
insert into program_day_exercises (program_day_id, exercise_id, position, letter, sets, reps) select pd.id, e.id, 1, 'B', 2, '12-15' from program_days pd, exercises e where pd.program_id = (select id from programs where slug = 'superman-6-day') and pd.slug = 'sat' and e.name = 'Seated Hip Abduction Machine';
insert into program_day_exercises (program_day_id, exercise_id, position, letter, sets, reps) select pd.id, e.id, 2, 'C', 2, '8-12' from program_days pd, exercises e where pd.program_id = (select id from programs where slug = 'superman-6-day') and pd.slug = 'sat' and e.name = 'Seated Leg Curl Machine';
insert into program_day_exercises (program_day_id, exercise_id, position, letter, sets, reps) select pd.id, e.id, 3, 'D', 2, '8-12' from program_days pd, exercises e where pd.program_id = (select id from programs where slug = 'superman-6-day') and pd.slug = 'sat' and e.name = 'Barbell RDL''s';
insert into program_day_exercises (program_day_id, exercise_id, position, letter, sets, reps) select pd.id, e.id, 4, 'E', 2, '8-12' from program_days pd, exercises e where pd.program_id = (select id from programs where slug = 'superman-6-day') and pd.slug = 'sat' and e.name = 'Hip Thrust Machine';

insert into programs (slug, name, description, days_per_week) values ('superman-5-day', 'Superman 5-Day Split', 'Five training days built around push, pull, legs, upper, and lower, using the same 26-exercise pool.', 5) on conflict (slug) do update set name = excluded.name, description = excluded.description, days_per_week = excluded.days_per_week;
insert into program_days (program_id, slug, code, name, tag, day_order) select id, 'push', 'DAY 1', 'Push', 'Chest, Shoulders & Triceps', 0 from programs where slug = 'superman-5-day' on conflict (program_id, slug) do update set code = excluded.code, name = excluded.name, tag = excluded.tag, day_order = excluded.day_order;
delete from program_day_exercises where program_day_id = (select id from program_days where program_id = (select id from programs where slug = 'superman-5-day') and slug = 'push');
insert into program_day_exercises (program_day_id, exercise_id, position, letter, sets, reps) select pd.id, e.id, 0, 'A', 2, '8-12' from program_days pd, exercises e where pd.program_id = (select id from programs where slug = 'superman-5-day') and pd.slug = 'push' and e.name = 'Incline Dumbbell Press';
insert into program_day_exercises (program_day_id, exercise_id, position, letter, sets, reps) select pd.id, e.id, 1, 'B', 3, '8-12' from program_days pd, exercises e where pd.program_id = (select id from programs where slug = 'superman-5-day') and pd.slug = 'push' and e.name = 'Pec Fly Machine';
insert into program_day_exercises (program_day_id, exercise_id, position, letter, sets, reps) select pd.id, e.id, 2, 'C', 2, '8-12' from program_days pd, exercises e where pd.program_id = (select id from programs where slug = 'superman-5-day') and pd.slug = 'push' and e.name = 'Shoulder Press Machine';
insert into program_day_exercises (program_day_id, exercise_id, position, letter, sets, reps) select pd.id, e.id, 3, 'D', 3, '12-15' from program_days pd, exercises e where pd.program_id = (select id from programs where slug = 'superman-5-day') and pd.slug = 'push' and e.name = 'Cable Standing Tricep Extension';
insert into program_day_exercises (program_day_id, exercise_id, position, letter, sets, reps) select pd.id, e.id, 4, 'E', 2, '12-15' from program_days pd, exercises e where pd.program_id = (select id from programs where slug = 'superman-5-day') and pd.slug = 'push' and e.name = 'Overhead Cable Tricep Extension';
insert into program_day_exercises (program_day_id, exercise_id, position, letter, sets, reps) select pd.id, e.id, 5, 'F', 2, '12-15' from program_days pd, exercises e where pd.program_id = (select id from programs where slug = 'superman-5-day') and pd.slug = 'push' and e.name = 'Cuffed Lateral Raise';

insert into program_days (program_id, slug, code, name, tag, day_order) select id, 'pull', 'DAY 2', 'Pull', 'Back & Biceps', 1 from programs where slug = 'superman-5-day' on conflict (program_id, slug) do update set code = excluded.code, name = excluded.name, tag = excluded.tag, day_order = excluded.day_order;
delete from program_day_exercises where program_day_id = (select id from program_days where program_id = (select id from programs where slug = 'superman-5-day') and slug = 'pull');
insert into program_day_exercises (program_day_id, exercise_id, position, letter, sets, reps) select pd.id, e.id, 0, 'A', 2, '8-12' from program_days pd, exercises e where pd.program_id = (select id from programs where slug = 'superman-5-day') and pd.slug = 'pull' and e.name = 'Chest Supported Landmine Row';
insert into program_day_exercises (program_day_id, exercise_id, position, letter, sets, reps) select pd.id, e.id, 1, 'B', 2, '8-12' from program_days pd, exercises e where pd.program_id = (select id from programs where slug = 'superman-5-day') and pd.slug = 'pull' and e.name = 'Lat Pull Down';
insert into program_day_exercises (program_day_id, exercise_id, position, letter, sets, reps) select pd.id, e.id, 2, 'C', 3, '12-15' from program_days pd, exercises e where pd.program_id = (select id from programs where slug = 'superman-5-day') and pd.slug = 'pull' and e.name = 'Preacher Curl Machine';
insert into program_day_exercises (program_day_id, exercise_id, position, letter, sets, reps) select pd.id, e.id, 3, 'D', 2, '12-15' from program_days pd, exercises e where pd.program_id = (select id from programs where slug = 'superman-5-day') and pd.slug = 'pull' and e.name = 'Rope Standing Cable Bicep Curl';
insert into program_day_exercises (program_day_id, exercise_id, position, letter, sets, reps) select pd.id, e.id, 4, 'E', 2, '12-15' from program_days pd, exercises e where pd.program_id = (select id from programs where slug = 'superman-5-day') and pd.slug = 'pull' and e.name = 'Barbell Shrugs';

insert into program_days (program_id, slug, code, name, tag, day_order) select id, 'legs', 'DAY 3', 'Legs', 'Quads Focus', 2 from programs where slug = 'superman-5-day' on conflict (program_id, slug) do update set code = excluded.code, name = excluded.name, tag = excluded.tag, day_order = excluded.day_order;
delete from program_day_exercises where program_day_id = (select id from program_days where program_id = (select id from programs where slug = 'superman-5-day') and slug = 'legs');
insert into program_day_exercises (program_day_id, exercise_id, position, letter, sets, reps) select pd.id, e.id, 0, 'A', 3, '8-12' from program_days pd, exercises e where pd.program_id = (select id from programs where slug = 'superman-5-day') and pd.slug = 'legs' and e.name = 'Leg Extension Machine';
insert into program_day_exercises (program_day_id, exercise_id, position, letter, sets, reps) select pd.id, e.id, 1, 'B', 2, '8-12' from program_days pd, exercises e where pd.program_id = (select id from programs where slug = 'superman-5-day') and pd.slug = 'legs' and e.name = 'Lying Leg Press Machine';
insert into program_day_exercises (program_day_id, exercise_id, position, letter, sets, reps) select pd.id, e.id, 2, 'C', 2, '8-12' from program_days pd, exercises e where pd.program_id = (select id from programs where slug = 'superman-5-day') and pd.slug = 'legs' and e.name = 'Dumbbell Walking Lunges';
insert into program_day_exercises (program_day_id, exercise_id, position, letter, sets, reps) select pd.id, e.id, 3, 'D', 2, '12-15' from program_days pd, exercises e where pd.program_id = (select id from programs where slug = 'superman-5-day') and pd.slug = 'legs' and e.name = 'Seated Hip Adduction Machine';
insert into program_day_exercises (program_day_id, exercise_id, position, letter, sets, reps) select pd.id, e.id, 4, 'E', 2, '12-15' from program_days pd, exercises e where pd.program_id = (select id from programs where slug = 'superman-5-day') and pd.slug = 'legs' and e.name = 'Seated Calf Raise (Leg Press Machine)';

insert into program_days (program_id, slug, code, name, tag, day_order) select id, 'upper', 'DAY 5', 'Upper', 'Full Upper Body', 3 from programs where slug = 'superman-5-day' on conflict (program_id, slug) do update set code = excluded.code, name = excluded.name, tag = excluded.tag, day_order = excluded.day_order;
delete from program_day_exercises where program_day_id = (select id from program_days where program_id = (select id from programs where slug = 'superman-5-day') and slug = 'upper');
insert into program_day_exercises (program_day_id, exercise_id, position, letter, sets, reps) select pd.id, e.id, 0, 'A', 2, '8-12' from program_days pd, exercises e where pd.program_id = (select id from programs where slug = 'superman-5-day') and pd.slug = 'upper' and e.name = 'Body Weight Push Up';
insert into program_day_exercises (program_day_id, exercise_id, position, letter, sets, reps) select pd.id, e.id, 1, 'B', 2, '8-12' from program_days pd, exercises e where pd.program_id = (select id from programs where slug = 'superman-5-day') and pd.slug = 'upper' and e.name = 'Chest Focused Dips';
insert into program_day_exercises (program_day_id, exercise_id, position, letter, sets, reps) select pd.id, e.id, 2, 'C', 2, '8-12' from program_days pd, exercises e where pd.program_id = (select id from programs where slug = 'superman-5-day') and pd.slug = 'upper' and e.name = 'Barbell Row';
insert into program_day_exercises (program_day_id, exercise_id, position, letter, sets, reps) select pd.id, e.id, 3, 'D', 2, '12-15' from program_days pd, exercises e where pd.program_id = (select id from programs where slug = 'superman-5-day') and pd.slug = 'upper' and e.name = 'Dumbbell Lateral Raise';
insert into program_day_exercises (program_day_id, exercise_id, position, letter, sets, reps) select pd.id, e.id, 4, 'E', 2, '12-15' from program_days pd, exercises e where pd.program_id = (select id from programs where slug = 'superman-5-day') and pd.slug = 'upper' and e.name = 'Incline Lying Dumbbell Bicep Curl';

insert into program_days (program_id, slug, code, name, tag, day_order) select id, 'lower', 'DAY 6', 'Lower', 'Hamstrings & Glutes Focus', 4 from programs where slug = 'superman-5-day' on conflict (program_id, slug) do update set code = excluded.code, name = excluded.name, tag = excluded.tag, day_order = excluded.day_order;
delete from program_day_exercises where program_day_id = (select id from program_days where program_id = (select id from programs where slug = 'superman-5-day') and slug = 'lower');
insert into program_day_exercises (program_day_id, exercise_id, position, letter, sets, reps) select pd.id, e.id, 0, 'A', 2, '8-12' from program_days pd, exercises e where pd.program_id = (select id from programs where slug = 'superman-5-day') and pd.slug = 'lower' and e.name = 'Barbell RDL''s';
insert into program_day_exercises (program_day_id, exercise_id, position, letter, sets, reps) select pd.id, e.id, 1, 'B', 2, '8-12' from program_days pd, exercises e where pd.program_id = (select id from programs where slug = 'superman-5-day') and pd.slug = 'lower' and e.name = 'Hip Thrust Machine';
insert into program_day_exercises (program_day_id, exercise_id, position, letter, sets, reps) select pd.id, e.id, 2, 'C', 2, '8-12' from program_days pd, exercises e where pd.program_id = (select id from programs where slug = 'superman-5-day') and pd.slug = 'lower' and e.name = 'Lying Leg Curl Machine';
insert into program_day_exercises (program_day_id, exercise_id, position, letter, sets, reps) select pd.id, e.id, 3, 'D', 2, '8-12' from program_days pd, exercises e where pd.program_id = (select id from programs where slug = 'superman-5-day') and pd.slug = 'lower' and e.name = 'Seated Leg Curl Machine';
insert into program_day_exercises (program_day_id, exercise_id, position, letter, sets, reps) select pd.id, e.id, 4, 'E', 2, '12-15' from program_days pd, exercises e where pd.program_id = (select id from programs where slug = 'superman-5-day') and pd.slug = 'lower' and e.name = 'Seated Hip Abduction Machine';
